### ISSUE TITLE
prepare_data() method error

### ISSUE THREAD

**Issue by gtdlk20** [ulfaslak/annadl_f19#2]
```
net1 = Network([2,1])

X, y = generate_X_linear(1e5)
X, y = prepare_data(X, y)
```

gives me this error: "ValueError: too many values to unpack (expected 2)."

When I pass it X[:2], y[:2] it spits out the respective tuple, but it can't digest the entire dataset. Any ideas?

**Comment by wsjung** [comment]
the `prepare_data` function returns a single list but you are trying to assign it to the tuple `X, y`.
