### ISSUE TITLE
feedforward function gives 3 values

### ISSUE THREAD

**Issue by sejaldua** [ulfaslak/annadl_f19#3]
Don't we want one prediction value after calling the `feedforward` function on a single point of our x vector? I am getting an array of 3 values. Does anyone know how to somehow squish this into 1 or are we supposed to work with 3?

**Comment by ulfaslak** [comment]
How did you instantiate your network? The `sizes` argument to `Network` when you instantiate it determines the number of neurons you want in each layer. So if you instantiated it along the lines of:

```Python
net = Network([2, 3])
```

Then you are asking for two layers of neurons (one layer of weights) where there are three output neurons: hence the trouble. But I'd need to see your code to confirm.

**Comment by sejaldua** [comment]
Ahh that explains it. Thank you.
