### ISSUE TITLE
nabla_ vs delta_nabla_?

### ISSUE THREAD

**Issue by gtdlk20** [ulfaslak/annadl_f19#4]
Can anybody say what the difference is between the two vectors in update_mini_batch?

**Comment by ulfaslak** [comment]
So in this loop:

```Python
for x, y in mini_batch:
    delta_nabla_b, delta_nabla_w = self.backprop(x, y)
    nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
    nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]
```

You are basically running each datapoint (x, y) in your mini batch through your network, and getting back the gradients for weights and biases. `delta_nabla_*` are the gradients for **each** datapoint. `nabla_*` are the **summed** gradients.

When we update the weights we actually divide by `len(mini_batch)`, so we end up subtracting the average gradients from the weights. Makes sense?

**Comment by gtdlk20** [comment]
Got it, thank you!
